version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    restart: always
    volumes:
      - app_data:/app/app/data
      - app_uploads:/app/app/uploads
      - app_static:/app/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app_network
    environment:
      - PYTHONUNBUFFERED=1  # Ensure logs are immediately visible

  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Use HTTP-only config
      - app_static:/app/app/static:ro
    depends_on:
      - web
    restart: always
    networks:
      - app_network

volumes:
  app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/docker_volumes/app_data
  app_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/docker_volumes/app_uploads
  app_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/docker_volumes/app_static

networks:
  app_network: