version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insta_analyzer_app
    restart: always
    expose:
      - "8000"
    volumes:
      - app_data:/app/app/data
      - app_uploads:/app/app/uploads
      - app_static:/app/app/static/images
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: insta_analyzer_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - app_static:/var/www/static:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  app_data:
    driver: local
  app_uploads:
    driver: local
  app_static:
    driver: local 