version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./app/static:/app/app/static
      - ./app/uploads:/app/app/uploads
      - ./app/data:/app/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - SECRET_KEY=${SECRET_KEY:-super-secret-key-please-change-in-prod}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///app.db}
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    command: /start.sh 