version: '3.8'

services:
  insta_influ_analyser:
    build: .
    container_name: insta_influ_analyser
    restart: always
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./app/uploads:/app/app/uploads
      - ./app/data:/app/app/data
      - ./app/static/images/posts:/app/app/static/images/posts
      - ./app/static/images/profiles:/app/app/static/images/profiles
      - ./app/static/images/brand:/app/app/static/images/brand 