services:
  app:
    build: .
    restart: always
    volumes:
      - ./docker_volumes/app_uploads:/app/uploads
      - ./docker_volumes/app_data:/app/data
      - ./docker_volumes/app_static:/app/static
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    networks:
      - app_network

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker_volumes/app_static:/app/static
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network: 