version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: insta_analyzer_app_dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/venv
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-key-for-local-testing
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN:-}
    restart: unless-stopped
    command: python run.py

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  app_data:
  app_uploads:
  app_static: 