services:
  debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    restart: "no"
    container_name: flask_debug
    ports:
      - "5001:5000"
    volumes:
      - ./docker_volumes/app_uploads:/app/app/uploads
      - ./docker_volumes/app_data:/app/app/data
      - ./docker_volumes/app_static:/app/app/static
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    # Debug with full logs
    command: python -u run_debug.py

networks:
  default:
    driver: bridge 