services:
  app:
    build: .
    restart: always
    container_name: flask_app
    expose:
      - "5000"  # Only expose to internal network, not to host
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./app/data:/app/app/data  # Add this mapping for user data
      - ./static:/app/static
      - ./app/static:/app/app/static  # Add this mapping for app static files
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    networks:
      - app_network

  nginx:
    image: nginx:1.25-alpine
    restart: always
    container_name: nginx
    ports:
      - "80:80"  # Map port 80 to host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/app/uploads
      - ./static:/app/static
      - ./app/static:/app/app/static  # Add this mapping for app static files
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge