services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./static:/app/static
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    command: python run.py 