version: '3.8'

services:
  web:
    build: .
    image: insta-influencer-analyzer:dev
    container_name: insta-analyzer-app-dev
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - app_data:/app/app/data
      - app_uploads:/app/app/uploads
      - app_images:/app/app/static/images
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=5000

  nginx:
    image: nginx:alpine
    container_name: insta-analyzer-nginx-dev
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/http.conf:/etc/nginx/conf.d/default.conf
      - app_images:/usr/share/nginx/html/static/images:ro
    depends_on:
      - web

volumes:
  app_data:
  app_uploads:
  app_images: 