version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    restart: always
    volumes:
      - app_data:/app/app/data
      - app_uploads:/app/app/uploads
      - app_images:/app/app/static/images
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app_network

  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # <- use HTTP-only config
      - app_images:/app/app/static/images:ro
    depends_on:
      - web
    restart: always
    networks:
      - app_network

volumes:
  app_data:
  app_uploads:
  app_images:

networks:
  app_network:
