name: CD - Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.AWS_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Add to known_hosts
      run: ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "
          cd ~/Insta_influ_analyser &&
          git pull &&
          source venv/bin/activate &&
          pip install -r requirements.txt &&
          sudo systemctl restart insta-analyzer
        "
        
    - name: Verify Deployment
      run: |
        echo "Deployment complete! Verifying service status..."
        ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "sudo systemctl status insta-analyzer"
    
    - name: Health Check
      id: health_check
      run: |
        for i in {1..5}; do
          response=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.AWS_HOST }})
          if [ "$response" == "200" ]; then
            echo "Health check passed!"
            exit 0
          fi
          echo "Waiting for service to start... attempt $i"
          sleep 10
        done
        echo "Health check failed after 5 attempts"
        exit 1
      continue-on-error: true

    - name: Rollback if Failed
      if: steps.health_check.outcome == 'failure'
      run: |
        ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "
          cd ~/Insta_influ_analyser &&
          git reset --hard HEAD~1 &&
          sudo systemctl restart insta-analyzer
        " 