name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Create app directory if it doesn't exist
            mkdir -p ~/Insta_influ_analyser

            # Clone or pull the latest code
            if [ -d "~/Insta_influ_analyser/.git" ]; then
              cd ~/Insta_influ_analyser
              git pull
            else
              git clone https://github.com/madushan-jaya-sri/Insta_influ_analyser.git ~/Insta_influ_analyser
              cd ~/Insta_influ_analyser
            fi
            
            # Build the Docker image locally
            docker build -t instagram-analyzer:latest .
            
            # Stop and remove the existing container if it's running
            docker stop instagram-analyzer || true
            docker rm instagram-analyzer || true
            
            # Run the new container with environment variables
            docker run -d \
              --name instagram-analyzer \
              -p 80:80 \
              -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
              -e APIFY_API_TOKEN="${{ secrets.APIFY_API_TOKEN }}" \
              -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
              -v instagram_data:/app/app/data \
              -v instagram_uploads:/app/app/uploads \
              -v instagram_images:/app/app/static/images \
              --restart unless-stopped \
              instagram-analyzer:latest
            
            # Remove unused images to save space
            docker image prune -af --filter "until=24h" 