name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 65.0.181.3 >> ~/.ssh/known_hosts
      
    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@65.0.181.3 '
          mkdir -p /home/ubuntu/Insta_influ_analyser
          cd /home/ubuntu/Insta_influ_analyser
          
          # Clone repo if it doesn't exist, otherwise pull
          if [ ! -d ".git" ]; then
            git clone https://github.com/${{ github.repository }} .
          else
            git fetch --all
            git reset --hard origin/main
          fi
          
          # Copy the .env file from backup if it exists, otherwise create from example
          if [ -f "/home/ubuntu/.env.backup" ]; then
            cp /home/ubuntu/.env.backup .env
          else
            cp .env.example .env
            # You would need to modify the .env file here if first deployment
          fi
          
          # Create required directories
          mkdir -p certbot/conf certbot/www
          
          # Deploy with Docker
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml build --no-cache
          docker-compose -f docker-compose.prod.yml up -d
          
          # Backup the .env file
          cp .env /home/ubuntu/.env.backup
        '
    
    - name: Clean up SSH keys
      run: rm -rf ~/.ssh 