name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create .env file
        run: |
          echo "Creating .env file..."
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "APIFY_API_TOKEN=${{ secrets.APIFY_API_TOKEN }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
      
      - name: Compress repository
        run: |
          tar -czf repository.tar.gz --exclude='.git' --exclude='.github' .
      
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "repository.tar.gz,.env"
          target: "~"
          
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            mkdir -p ~/Insta_influ_analyser
            tar -xzf ~/repository.tar.gz -C ~/Insta_influ_analyser
            cp ~/.env ~/Insta_influ_analyser/.env
            cd ~/Insta_influ_analyser
            echo "Stopping existing Docker containers..."
            docker-compose down || true
            echo "Building and starting new Docker containers..."
            docker-compose up --build -d
            echo "Cleaning up..."
            docker image prune -f
            rm ~/repository.tar.gz
            echo "Deployment completed successfully!" 