name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Add host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "mkdir -p ~/Insta_influ_analyser"
          rsync -avz --exclude '.git/' --exclude 'venv/' --exclude '__pycache__/' \
            --exclude 'uploads/' --exclude 'data/' --exclude 'docker_volumes/' \
            ./ ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }}:~/Insta_influ_analyser/

      - name: Create .env file on EC2
        run: |
          ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "echo 'FLASK_ENV=production' > ~/Insta_influ_analyser/.env"
          ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> ~/Insta_influ_analyser/.env"
          ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "echo 'OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}' >> ~/Insta_influ_analyser/.env"
          ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "echo 'APIFY_API_TOKEN=${{ secrets.APIFY_API_TOKEN }}' >> ~/Insta_influ_analyser/.env"
          ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "echo 'AWS_HOST=${{ secrets.AWS_HOST }}' >> ~/Insta_influ_analyser/.env"
          ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "echo 'AWS_USERNAME=${{ secrets.AWS_USERNAME }}' >> ~/Insta_influ_analyser/.env"

      - name: Run deploy script on EC2
        run: |
          ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "cd ~/Insta_influ_analyser && bash scripts/deploy.sh"

      - name: Fix permissions and create required files
        run: |
          ssh ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "cd ~/Insta_influ_analyser && bash scripts/fix_permissions.sh"