name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Updated deployment to use nginx.conf from repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            echo "Starting deployment process..."
            
            # Set up working directories
            WORK_DIR="$HOME/fresh_deployment"
            DATA_DIR="$HOME/app_persistent_data"
            
            # Create persistent data directory if it doesn't exist
            mkdir -p "$DATA_DIR/static/images/brand"
            mkdir -p "$DATA_DIR/uploads"
            mkdir -p "$DATA_DIR/data"
            
            # Force proper permissions on data directory
            sudo chown -R $(whoami):$(whoami) "$DATA_DIR"
            chmod -R 777 "$DATA_DIR"
            
            # Clean previous deployment directory
            rm -rf "$WORK_DIR"
            mkdir -p "$WORK_DIR"
            cd "$WORK_DIR"
            
            # Clone repository
            echo "Cloning fresh repository..."
            git clone https://github.com/madushan-jaya-sri/Insta_influ_analyser.git .
            
            if [ ! -d app ]; then
              echo "ERROR: Repository cloning failed or app directory missing!"
              exit 1
            fi
            
            echo "Repository successfully cloned."
            git log -1 --oneline
            
            # Fix auth.py indentation
            echo "Fixing auth.py indentation..."
            mkdir -p app/routes
            cat > app/routes/auth.py << 'EOF'
            from flask import (
                Blueprint, render_template, redirect, url_for, request,
                flash, session, current_app
            )
            from flask_login import login_user, logout_user, login_required, current_user
            from werkzeug.urls import url_parse

            # Updated imports for models and forms
            from app.forms import LoginForm, RegistrationForm
            from app.models.user import User
            from app.models.history import History # Import History if needed here, or likely in main.py
            from run import db # Import db instance from run.py

            # Keep the blueprint name, but ensure url_prefix matches run.py if set there
            # The url_prefix='/auth' was added in run.py, so it's correct here.
            auth_bp = Blueprint('auth', __name__)

            @auth_bp.route('/login', methods=['GET', 'POST'])
            def login():
                if current_user.is_authenticated:
                    return redirect(url_for('main.index')) # Redirect to main index or dashboard
                
                form = LoginForm()
                if form.validate_on_submit():
                    # Use SQLAlchemy query to find the user
                    user = db.session.scalar(db.select(User).where(User.username == form.username.data))

                    if user is None or not user.check_password(form.password.data):
                        flash('Invalid username or password', 'danger')
                        return redirect(url_for('auth.login'))

                    # Log the user in using Flask-Login
                    login_user(user, remember=form.remember_me.data)
                    flash(f'Welcome back, {user.username}!', 'success')

                    # Redirect to the page the user was trying to access, or index
                    next_page = request.args.get('next')
                    if not next_page or url_parse(next_page).netloc != '':
                        next_page = url_for('main.index') # Or main.dashboard if that exists
                    return redirect(next_page)
                
                return render_template('auth/login.html', title='Sign In', form=form)

            @auth_bp.route('/register', methods=['GET', 'POST'])
            def register():
                if current_user.is_authenticated:
                    return redirect(url_for('main.index')) # Redirect to main index or dashboard
                
                form = RegistrationForm()
                if form.validate_on_submit():
                    try:
                        user = User(username=form.username.data, email=form.email.data)
                        user.set_password(form.password.data)
                        db.session.add(user)
                        db.session.commit()
                        flash(f'Congratulations, {user.username}, you are now a registered user!', 'success')
                        # Log the user in immediately after registration
                        login_user(user)
                        return redirect(url_for('main.index')) # Redirect to main index or dashboard
                    except Exception as e:
                        db.session.rollback() # Rollback in case of error
                        flash('An error occurred during registration. Please try again.', 'danger')
                        current_app.logger.error(f"Registration error: {str(e)}")
                
                return render_template('auth/register.html', title='Register', form=form)

            @auth_bp.route('/logout')
            @login_required
            def logout():
                logout_user()
                flash('You have been logged out.', 'info')
                return redirect(url_for('main.index'))
            EOF
            
            # Ensure we have a requirements.txt file
            if [ ! -f requirements.txt ]; then
              echo "Creating requirements.txt..."
              cat > requirements.txt << 'EOF'
              Flask==2.0.1
              Flask-Login==0.5.0
              Flask-SQLAlchemy==2.5.1
              gunicorn==21.2.0
              ipython==8.18.1
              SQLAlchemy==2.0.4
              Werkzeug==2.0.1
              EOF
            else
              # Fix ipython version
              sed -i 's/ipython==9.1.0/ipython==8.18.1/g' requirements.txt
            fi
            
            # Copy static files if they exist
            if [ -d app/static ]; then
              echo "Copying static files to persistent data directory..."
              cp -r app/static/* "$DATA_DIR/static/"
            fi
            
            # Ensure logo files exist in data directory
            echo "Checking for logo files..."
            if [ ! -f "$DATA_DIR/static/images/brand/momentro-logo.png" ]; then
              echo "Logo files missing, looking for them in repository..."
              
              # Look for logo files in the repository
              LOGO_FILE=$(find . -name "momentro-logo.png" | head -1)
              if [ -n "$LOGO_FILE" ]; then
                echo "Found logo file at $LOGO_FILE"
                cp "$LOGO_FILE" "$DATA_DIR/static/images/brand/momentro-logo.png"
                cp "$LOGO_FILE" "$DATA_DIR/static/images/brand/momentro_logo.png"
              else
                echo "No logo file found, downloading placeholder image..."
                curl -s https://via.placeholder.com/150 -o "$DATA_DIR/static/images/brand/momentro-logo.png"
                curl -s https://via.placeholder.com/150 -o "$DATA_DIR/static/images/brand/momentro_logo.png"
              fi
            fi
            
            # Ensure proper permissions
            chmod -R 777 "$DATA_DIR"
            
            # Create WSGI file
            cat > wsgi.py << 'EOF'
            #!/usr/bin/env python3
            import os
            import sys
            
            # Add the current directory to the path
            sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))
            
            # Import the create_app function from run.py
            from run import create_app
            
            # Create the application instance
            application = create_app()
            
            # For Gunicorn
            app = application
            
            if __name__ == "__main__":
                app.run()
            EOF
            
            # Create Flask app's Dockerfile
            cat > Dockerfile.app << 'EOF'
            FROM python:3.10-slim

            # Set working directory
            WORKDIR /app

            # Install dependencies
            COPY requirements.txt .
            RUN pip install --upgrade pip && \
                pip install --no-cache-dir gunicorn Flask==2.0.1 Flask-Login==0.5.0 Flask-SQLAlchemy==2.5.1 && \
                pip install --no-cache-dir -r requirements.txt || pip install --no-cache-dir -r requirements.txt --no-deps

            # Copy application code
            COPY . .
            
            # Expose port
            EXPOSE 8000

            # Start Gunicorn
            CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--timeout", "120", "--workers", "3", "--log-level", "info", "wsgi:app"]
            EOF
            
            # Create nginx.conf
            cat > docker-nginx.conf << 'EOF'
            server {
                listen 80;
                server_name localhost;
                
                # Debug information location
                location = /debug {
                    add_header Content-Type text/plain;
                    add_header X-Debug-Static "Static files debug page";
                    return 200 "Debug static files";
                }
                
                # Specific locations for exact logo files
                location = /static/images/brand/momentro-logo.png {
                    root /usr/share/nginx/html;
                    add_header Content-Type image/png;
                    expires 30d;
                    access_log on;
                }

                location = /static/images/brand/momentro_logo.png {
                    root /usr/share/nginx/html;
                    add_header Content-Type image/png;
                    expires 30d;
                    access_log on;
                }
                
                # Serve static files directly
                location /static/ {
                    root /usr/share/nginx/html;
                    expires 30d;
                    try_files $uri =404;
                    add_header Cache-Control "public, max-age=31536000";
                }
                
                location /uploads/ {
                    root /usr/share/nginx/html;
                    expires 30d;
                }
                
                # Everything else to Flask app
                location / {
                    proxy_pass http://flask-app:8000;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
            EOF
            
            # Create docker-compose.yml
            cat > docker-compose.yml << EOF
            version: '3'

            services:
              flask-app:
                container_name: instagram-app
                build:
                  context: .
                  dockerfile: Dockerfile.app
                restart: unless-stopped
                environment:
                  - SECRET_KEY=${{ secrets.SECRET_KEY }}
                  - APIFY_API_TOKEN=${{ secrets.APIFY_API_TOKEN }}
                  - OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
                volumes:
                  - $DATA_DIR/static:/app/app/static
                  - $DATA_DIR/uploads:/app/app/uploads
                  - $DATA_DIR/data:/app/app/data
                networks:
                  - app-network

              nginx:
                container_name: instagram-nginx
                image: nginx:alpine
                restart: unless-stopped
                ports:
                  - "80:80"
                volumes:
                  - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf
                  - $DATA_DIR/static:/usr/share/nginx/html/static
                  - $DATA_DIR/uploads:/usr/share/nginx/html/uploads
                depends_on:
                  - flask-app
                networks:
                  - app-network

            networks:
              app-network:
                driver: bridge
            EOF
            
            # Stop and remove any existing containers
            echo "Stopping existing containers..."
            docker stop instagram-app instagram-nginx 2>/dev/null || true
            docker rm instagram-app instagram-nginx 2>/dev/null || true
            
            # Build and start containers
            echo "Building and starting Docker containers..."
            docker-compose down -v 2>/dev/null || true
            docker-compose build --no-cache
            
            if [ $? -ne 0 ]; then
              echo "ERROR: Docker compose build failed!"
              exit 1
            fi
            
            docker-compose up -d
            
            if [ $? -ne 0 ]; then
              echo "ERROR: Docker compose up failed!"
              exit 1
            fi
            
            # Wait for containers to start
            echo "Waiting for containers to start..."
            sleep 15
            
            # Check if containers are running
            docker ps
            
            RUNNING_CONTAINERS=$(docker ps -q --filter name=instagram)
            if [ -z "$RUNNING_CONTAINERS" ]; then
              echo "ERROR: Containers are not running!"
              docker-compose logs
              exit 1
            fi
            
            # Test static file access
            echo "Testing static file access..."
            curl -I localhost/static/images/brand/momentro-logo.png
            
            echo "Deployment completed successfully!" 